[package]
name = "valine_bot"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0"
similar = "2.6.0"
dashmap = "6.1.0"
itertools = "0.13"
serenity = { version = "0.12.2" }
tracing = "0.1.40"
tracing-subscriber = "0.3"
serde_with = "3"
toml = "0.8"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "signal"] }
serde = { version = "1.0", features = ["derive"] }
bpaf = { version = "0.9", features = ["derive"] }

[profile.release]
panic = "abort"
strip = true
opt-level = "z"
lto = true
codegen-units = 1
