
[bot]
token = "TOKEN"
application_id = "000000000000000000"


[auth]
# 認証に使用するチャンネルID
channel_id = "000000000000000000"
# 認証の結果を通知するチャンネルID
log_channel_id = "000000000000000000"
# 認証後に付与するロールID
role_id = "000000000000000000"
# 認証に成功したメッセージに付与するリアクション
authenticated_reaction = "<:verified:000000000000000000>"
# マッチしたら認証成功とする正規表現
trigger_regex = "[おオｵ][のノﾉ][れレﾚ][GgＧｇ][RrＲｒ][EeＥｅ][GgＧｇ]"


[message_logging]
# メッセージの削除・編集のログを残すチャンネルID
channel_id = "000000000000000000"


[message_cache]
# キャッシュを無効化するかどうか
disabled = true
# 過去のメッセージのキャッシュを取るギルドIDのリスト
target_guild_ids = ["000000000000000000"]


[thread_channel_startup]
# 空にする方法
# threads = []

[[thread_channel_startup.threads]]
# 初期メッセージを投稿するスレッドチャンネルのID
channel_id = "000000000000000000"
# 初期メッセージの内容
startup_message = """スレッドの始まりだぁ！
まずはこのテンプレートを読んでね！"""
